### PR TITLE
Brought it into the Scaffold because we use it all the time

### PR DESCRIPTION
**Pull request by jhogue**
Worked on this for BCBS.com. This mixin tries to emulate the way native background-cover works.

### CODE REVIEW

**Review by johncionci — COMMENTED** [review]
Looks good from here, any thoughts on making this its own file?

Probably a separate issue but I think the InVision blog is one that we typically try to emulate as well so maybe writing some scripts to recreate this functionality. http://blog.invisionapp.com/mr-robot-productivity/

**Comment by jhogue** [comment]
Its own file? Nah… one global mixins file that we use for every project is enough. I think what we should do, however, is break out project mixins (per project) from the global ones here. 

What's the Mr Robot thing?

**Comment by johncionci** [comment]
Thats just a link to a blog post from InVison App. Good article on productivity, but also think that they have a very solid hero implementation. Based on scroll, animations, responsive and such.

**Comment by jhogue** [comment]
Oh oh oh. Gotcha. Would love to… but I won't have the time right now :)

**Comment by johncionci** [comment]
#aintnobodygottimefordat!

**Pull request merged**
