### PR TITLE
Move mixin to the proper file and variables to the proper file

### PR DESCRIPTION
**Pull request by nicholemaureen**
We had them all in the buttons file, which is a bit inconsistent with everything else we've done

### CODE REVIEW

**Comment by kalilsn** [comment]
🚮 lgtm!! /approved

**Comment by balbuf** [comment]
what are you trying to convey with that emoji @kalilsn ?!

**Comment by kalilsn** [comment]
"put litter in its place" is my go-to organizing emoji

**Comment by nicholemaureen** [comment]
inspiring

**Pull request merged**
