### PR TITLE
40 restructure into 6 1 pattern

### PR DESCRIPTION
**Pull request by jhogue**
Implemented a new 6/1 pattern for organizing files. 

- Abstracts: all files that are functions, mixins, or variable declarations
- Base: CSS reset, basic default typography, best practice form elements & helpers
- Components: project elements
- Layout: Basic grid and/or global component layout & breakpoint usage
- Pages: Exceptions to global component rules on a per page basis
- Vendor: Scaffold requirements and/or 3rd party libraries/tools

Along the way, a few declaration improvements to avoid double-declaring similar reset styles. 

Closes Issue #40

### CODE REVIEW

**Comment by raubin** [comment]
@jhogue - which is it: a 6-1 or a 7-1 (as described in your issue)? If we're going to be influenced by a convention, we should just adopt it, not modify-and-adopt. It further fragments our process and creates a need to onboard new people to something they wouldn't see elsewhere.

**Comment by jhogue** [comment]
The 7-1 pattern that is common in the industry does not apply to us. I used a simpler 6-1 pattern here. Most of the team bought into the original idea.

**Comment by johncionci** [comment]
@jhogue 

Lets make sure that `/vendor/` is where things are going to end up in the future, on Coolidge bower is used so they end up in the `bower_components`. This of course is nullified if we rip out Bourbon/Neat

**Comment by jhogue** [comment]
Oh, interesting. Thanks John. I would think we still need `/vendor/` when we use something like Bootstrap for a project, or any BS component, or Slick/Flexslider and the like.

**Comment by jhogue** [comment]
Removed conflicts @johncionci

**Comment by johncionci** [comment]
LGTM! /approved

**Pull request merged**
