### PR TITLE
Reorganize Visual Grid

### PR DESCRIPTION
**Pull request by johncionci**
- add settings file
- move grid settings into settings file so we can use the visual grid

Resolves:
https://github.com/oomphinc/scss-scaffold/issues/19

Test:
Follow readme and compile locally - make sure it dont blow up :)

### CODE REVIEW

**Comment by jhogue** [comment]
Cool, but is there more? Like, where do you actually use a variable like `$visual-grid-color`?

**Comment by nicholemaureen** [comment]
I think bourbon is probably calling them

**Comment by johncionci** [comment]
@jhogue Neat is using those, so if you set the `$visual-grid: false;` to `true`, Neat would use the vars that you have declared to display the grid overlay. Essentially adds a `::before` to the body tag.

**Pull request merged**
